// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:27e5306a-f4af-43d7-a1cc-b6f83b415ed3",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_LGyYIpzov",
    "aws_user_pools_web_client_id": "6uf8smmf1brbq83ju297dr5n9c",
    "oauth": {}
};


export default awsmobile;
